<?php


namespace app\entrance;


use app\BaseController;
use app\rmcore\business\Login;
use think\facade\View;

class Base extends BaseController
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        Login::isLogin();
    }





    function __call($name, $arguments)
    {
        // TODO: Implement __call() method.
        if(request()->isPost()){
            return result_json('0','not fund !!','','');
        }
        View::config(['view_path' => root_path()]);
        return view("/app/rmcore/view/404");
    }


    /**
     * 系统404
     * @return \think\response\View
     */
    function  show_404(): \think\response\View
    {
        View::config(['view_path' => root_path()]);
        return view("/app/rmcore/view/404");
    }



}